import { SoftwareApplication as SoftwareApplicationType, LinkedEntity } from 'generated/backofficeSchemas';

export class SoftwareApplication implements SoftwareApplicationType {
  constructor(
    public author?: LinkedEntity[],
    public category?: LinkedEntity[],
    public changeComment?: string,
    public changeTimestamp?: string,
    public citation?: string[],
    public contactPoint?: LinkedEntity[],
    public contributor?: LinkedEntity[],
    public creator?: LinkedEntity[],
    public description?: string,
    public downloadURL?: string,
    public editorId?: string,
    public fileProvenance?: string,
    public fileSize?: string,
    public funder?: LinkedEntity[],
    public groups?: Array<string>,
    public identifier?: LinkedEntity[],
    public inputParameter?: LinkedEntity[],
    public installURL?: string,
    public instanceChangedId?: string,
    public instanceId?: string,
    public keywords?: string,
    public licenseURL?: string,
    public mainEntityOfPage?: string,
    public maintainer?: LinkedEntity[],
    public memoryrequirements?: string,
    public metaId?: string,
    public name?: string,
    public operatingSystem?: string[],
    public operation?: string,
    public outputParameter?: LinkedEntity[],
    public parameter?: LinkedEntity[],
    public processorRequirements?: string,
    public provider?: LinkedEntity[],
    public publisher?: LinkedEntity[],
    public relatedOperation?: LinkedEntity[],
    public requirements?: string,
    public softwareStatus?: string,
    public softwareVersion?: string,
    public spatial?: string,
    public status?: 'ARCHIVED' | 'DISCARDED' | 'DRAFT' | 'SUBMITTED' | 'PUBLISHED' | 'PENDING' | undefined,
    public storageRequirements?: string,
    public temporal?: string,
    public timeRequired?: string,
    public toBeDelete?: string,
    public uid?: string,
    public version?: string,
    public versionId?: string,
  ) {}
}
