import { SoftwareSourceCode as SoftwareSourceCodeType, LinkedEntity } from 'generated/backofficeSchemas';

export class SoftwareSourceCode implements SoftwareSourceCodeType {
  constructor(
    public author?: LinkedEntity[] | undefined,
    public category?: LinkedEntity[] | undefined,
    public changeComment?: string | undefined,
    public changeTimestamp?: string | undefined,
    public citation?: string[] | undefined,
    public codeRepository?: string | undefined,
    public contactPoint?: LinkedEntity[] | undefined,
    public contributor?: LinkedEntity[] | undefined,
    public creator?: LinkedEntity[] | undefined,
    public description?: string | undefined,
    public downloadURL?: string | undefined,
    public editorId?: string | undefined,
    public fileProvenance?: string | undefined,
    public funder?: LinkedEntity[] | undefined,
    public groups?: Array<string> | undefined,
    public identifier?: LinkedEntity[] | undefined,
    public instanceChangedId?: string | undefined,
    public instanceId?: string | undefined,
    public keywords?: string | undefined,
    public licenseURL?: string | undefined,
    public mainEntityofPage?: string | undefined,
    public maintainer?: LinkedEntity[] | undefined,
    public metaId?: string | undefined,
    public name?: string | undefined,
    public operation?: string | undefined,
    public programmingLanguage?: string[] | undefined,
    public provider?: LinkedEntity[] | undefined,
    public publisher?: LinkedEntity[] | undefined,
    public relation?: LinkedEntity[] | undefined,
    public runtimePlatform?: string | undefined,
    public size?: string | undefined,
    public softwareRequirements?: string | undefined,
    public softwareStatus?: string | undefined,
    public softwareVersion?: string | undefined,
    public spatial?: string | undefined,
    public status?: 'ARCHIVED' | 'DISCARDED' | 'DRAFT' | 'SUBMITTED' | 'PUBLISHED' | 'PENDING' | undefined,
    public temporal?: string | undefined,
    public timeRequired?: string | undefined,
    public toBeDelete?: string | undefined,
    public uid?: string | undefined,
    public version?: string | undefined,
    public versionId?: string | undefined,
  ) {}
}
